publish_to: none
name: rum_sdk
description: A new Flutter plugin project.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  device_info_plus: ^10.1.2
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  package_info_plus: ^8.0.1
  plugin_platform_interface: ^2.0.2
  uuid: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.8
  fake_async: ^1.3.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter:
  plugin:
    platforms:
      android:
        package: com.example.rum_sdk
        pluginClass: RumSdkPlugin
      ios:
        pluginClass: RumSdkPlugin
      linux:
        pluginClass: RumSdkPlugin
      macos:
        pluginClass: RumSdkPlugin
      windows:
        pluginClass: RumSdkPluginCApi
