name: Publish to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*" # Matches version tags like v1.2.3, v1.2.3-beta.1

jobs:
  publish:
    permissions:
      id-token: write # Required for OIDC authentication
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1.7.1
    with:
      environment: pub.dev
