name: Publish to pub.dev

permissions:
  contents: write
  packages: write

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    # Only run if the PR was merged and had the version-bump label
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'version-bump')
    runs-on: ubuntu-latest
    steps:
      - name: Get secrets from Vault
        uses: grafana/shared-workflows/actions/get-vault-secrets@5d7e361bc7e0a183cde8afe9899fb7b596d2659b # v1.2.0
        with:
          repo_secrets: |
            PUB_DEV_CREDENTIALS=pub-dev-credentials:value

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup Flutter
        uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046 # v2.19.0
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Get version from pubspec
        id: get_version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | sed 's/version: //')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pub credentials
        run: |
          mkdir -p $HOME/.config/dart
          echo "${{ env.PUB_DEV_CREDENTIALS }}" | base64 -d > $HOME/.config/dart/pub-credentials.json

      - name: Validate package (dry run)
        run: flutter pub publish --dry-run

      - name: Publish to pub.dev
        run: flutter pub publish --force
