name: Version Bump PR

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: "Version bump type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  create-version-bump-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup Flutter
        uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046 # v2.19.0
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Run version bump script
        env:
          BUMP_TYPE: ${{ github.event.inputs.bump_type }}
        run: |
          if [[ "$BUMP_TYPE" == "patch" || "$BUMP_TYPE" == "minor" || "$BUMP_TYPE" == "major" ]]; then
            dart tool/version_bump.dart $BUMP_TYPE
          else
            echo "Invalid bump type: $BUMP_TYPE"
            exit 1
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: bump version (${{ github.event.inputs.bump_type }})"
          title: "chore: bump version (${{ github.event.inputs.bump_type }})"
          body: |
            This PR bumps the version via the `version_bump.dart` script.

            - Version bump type: ${{ github.event.inputs.bump_type }}
            - Triggered by: @${{ github.actor }}
          branch: "version-bump/${{ github.run_id }}"
          base: main
          labels: "version-bump,automated-pr"
